/*
 * If not stated otherwise in this file or this component's license file the
 * following copyright and licenses apply:
 *
 * Copyright 2014 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
#ifndef _CTRLM_IPC_KEY_CODES_H_
#define _CTRLM_IPC_KEY_CODES_H_

/// @file ctrlm_ipc_key_codes.h

/// @brief Control Manager Key Codes
/// @details An enumeration of the key codes that are used in Control Manager.
typedef enum {
   CTRLM_KEY_CODE_OK               = 0x00,
   CTRLM_KEY_CODE_UP_ARROW         = 0x01,
   CTRLM_KEY_CODE_DOWN_ARROW       = 0x02,
   CTRLM_KEY_CODE_LEFT_ARROW       = 0x03,
   CTRLM_KEY_CODE_RIGHT_ARROW      = 0x04,
   CTRLM_KEY_CODE_MENU             = 0x09,
   CTRLM_KEY_CODE_DVR              = 0x0B,
   CTRLM_KEY_CODE_FAV              = 0x0C,
   CTRLM_KEY_CODE_EXIT             = 0x0D,
   CTRLM_KEY_CODE_HOME             = 0x10,
   CTRLM_KEY_CODE_DIGIT_0          = 0x20,
   CTRLM_KEY_CODE_DIGIT_1          = 0x21,
   CTRLM_KEY_CODE_DIGIT_2          = 0x22,
   CTRLM_KEY_CODE_DIGIT_3          = 0x23,
   CTRLM_KEY_CODE_DIGIT_4          = 0x24,
   CTRLM_KEY_CODE_DIGIT_5          = 0x25,
   CTRLM_KEY_CODE_DIGIT_6          = 0x26,
   CTRLM_KEY_CODE_DIGIT_7          = 0x27,
   CTRLM_KEY_CODE_DIGIT_8          = 0x28,
   CTRLM_KEY_CODE_DIGIT_9          = 0x29,
   CTRLM_KEY_CODE_PERIOD           = 0x2A,
   CTRLM_KEY_CODE_RETURN           = 0x2B,
   CTRLM_KEY_CODE_CH_UP            = 0x30,
   CTRLM_KEY_CODE_CH_DOWN          = 0x31,
   CTRLM_KEY_CODE_LAST             = 0x32,
   CTRLM_KEY_CODE_LANG             = 0x33,
   CTRLM_KEY_CODE_INPUT_SELECT     = 0x34,
   CTRLM_KEY_CODE_INFO             = 0x35,
   CTRLM_KEY_CODE_HELP             = 0x36,
   CTRLM_KEY_CODE_PAGE_UP          = 0x37,
   CTRLM_KEY_CODE_PAGE_DOWN        = 0x38,
   CTRLM_KEY_CODE_MOTION           = 0x3B,
   CTRLM_KEY_CODE_SEARCH           = 0x3C,
   CTRLM_KEY_CODE_LIVE             = 0x3D,
   CTRLM_KEY_CODE_HD_ZOOM          = 0x3E,
   CTRLM_KEY_CODE_SHARE            = 0x3F,
   CTRLM_KEY_CODE_TV_POWER         = 0x40,
   CTRLM_KEY_CODE_VOL_UP           = 0x41,
   CTRLM_KEY_CODE_VOL_DOWN         = 0x42,
   CTRLM_KEY_CODE_MUTE             = 0x43,
   CTRLM_KEY_CODE_PLAY             = 0x44,
   CTRLM_KEY_CODE_STOP             = 0x45,
   CTRLM_KEY_CODE_PAUSE            = 0x46,
   CTRLM_KEY_CODE_RECORD           = 0x47,
   CTRLM_KEY_CODE_REWIND           = 0x48,
   CTRLM_KEY_CODE_FAST_FORWARD     = 0x49,
   CTRLM_KEY_CODE_30_SEC_SKIP      = 0x4B,
   CTRLM_KEY_CODE_REPLAY           = 0x4C,
   CTRLM_KEY_CODE_TV_POWER_ON      = 0x4D,
   CTRLM_KEY_CODE_TV_POWER_OFF     = 0x4E,
   CTRLM_KEY_CODE_SWAP             = 0x51,
   CTRLM_KEY_CODE_ON_DEMAND        = 0x52,
   CTRLM_KEY_CODE_GUIDE            = 0x53,
   CTRLM_KEY_CODE_PUSH_TO_TALK     = 0x57,
   CTRLM_KEY_CODE_PIP_ON_OFF       = 0x58,
   CTRLM_KEY_CODE_PIP_MOVE         = 0x59,
   CTRLM_KEY_CODE_PIP_CH_UP        = 0x5A,
   CTRLM_KEY_CODE_PIP_CH_DOWN      = 0x5B,
   CTRLM_KEY_CODE_LOCK             = 0x5C,
   CTRLM_KEY_CODE_DAY_PLUS         = 0x5D,
   CTRLM_KEY_CODE_DAY_MINUS        = 0x5E,
   CTRLM_KEY_CODE_PLAY_PAUSE       = 0x61,
   CTRLM_KEY_CODE_STOP_VIDEO       = 0x64,
   CTRLM_KEY_CODE_MUTE_MIC         = 0x65,
   CTRLM_KEY_CODE_AVR_POWER_TOGGLE = 0x68,
   CTRLM_KEY_CODE_AVR_POWER_OFF    = 0x69,
   CTRLM_KEY_CODE_AVR_POWER_ON     = 0x6A,
   CTRLM_KEY_CODE_POWER_TOGGLE     = 0x6B,
   CTRLM_KEY_CODE_POWER_OFF        = 0x6C,
   CTRLM_KEY_CODE_POWER_ON         = 0x6D,
   CTRLM_KEY_CODE_OCAP_B           = 0x71,
   CTRLM_KEY_CODE_OCAP_C           = 0x72,
   CTRLM_KEY_CODE_OCAP_D           = 0x73,
   CTRLM_KEY_CODE_OCAP_A           = 0x74,
   CTRLM_KEY_CODE_CC               = 0x90,
   CTRLM_KEY_CODE_PROFILE          = 0xA0,
   CTRLM_KEY_CODE_CALL             = 0xA1,
   CTRLM_KEY_CODE_HOLD             = 0xA2,
   CTRLM_KEY_CODE_END              = 0xA3,
   CTRLM_KEY_CODE_VIEWS            = 0xA4,
   CTRLM_KEY_CODE_SELF_VIEW        = 0xA5,
   CTRLM_KEY_CODE_ZOOM_IN          = 0xA6,
   CTRLM_KEY_CODE_ZOOM_OUT         = 0xA7,
   CTRLM_KEY_CODE_BACKSPACE        = 0xA8,
   CTRLM_KEY_CODE_LOCK_UNLOCK      = 0xA9,
   CTRLM_KEY_CODE_CAPS             = 0xAA,
   CTRLM_KEY_CODE_ALT              = 0xAB,
   CTRLM_KEY_CODE_SPACE            = 0xAC,
   CTRLM_KEY_CODE_WWW_DOT          = 0xAD,
   CTRLM_KEY_CODE_DOT_COM          = 0xAE,
   CTRLM_KEY_CODE_UPPER_A          = 0xB0,
   CTRLM_KEY_CODE_UPPER_B          = 0xB1,
   CTRLM_KEY_CODE_UPPER_C          = 0xB2,
   CTRLM_KEY_CODE_UPPER_D          = 0xB3,
   CTRLM_KEY_CODE_UPPER_E          = 0xB4,
   CTRLM_KEY_CODE_UPPER_F          = 0xB5,
   CTRLM_KEY_CODE_UPPER_G          = 0xB6,
   CTRLM_KEY_CODE_UPPER_H          = 0xB7,
   CTRLM_KEY_CODE_UPPER_I          = 0xB8,
   CTRLM_KEY_CODE_UPPER_J          = 0xB9,
   CTRLM_KEY_CODE_UPPER_K          = 0xBA,
   CTRLM_KEY_CODE_UPPER_L          = 0xBB,
   CTRLM_KEY_CODE_UPPER_M          = 0xBC,
   CTRLM_KEY_CODE_UPPER_N          = 0xBD,
   CTRLM_KEY_CODE_UPPER_O          = 0xBE,
   CTRLM_KEY_CODE_UPPER_P          = 0xBF,
   CTRLM_KEY_CODE_UPPER_Q          = 0xC0,
   CTRLM_KEY_CODE_UPPER_R          = 0xC1,
   CTRLM_KEY_CODE_UPPER_S          = 0xC2,
   CTRLM_KEY_CODE_UPPER_T          = 0xC3,
   CTRLM_KEY_CODE_UPPER_U          = 0xC4,
   CTRLM_KEY_CODE_UPPER_V          = 0xC5,
   CTRLM_KEY_CODE_UPPER_W          = 0xC6,
   CTRLM_KEY_CODE_UPPER_X          = 0xC7,
   CTRLM_KEY_CODE_UPPER_Y          = 0xC8,
   CTRLM_KEY_CODE_UPPER_Z          = 0xC9,
   CTRLM_KEY_CODE_LOWER_A          = 0xCA,
   CTRLM_KEY_CODE_LOWER_B          = 0xCB,
   CTRLM_KEY_CODE_LOWER_C          = 0xCC,
   CTRLM_KEY_CODE_LOWER_D          = 0xCD,
   CTRLM_KEY_CODE_LOWER_E          = 0xCE,
   CTRLM_KEY_CODE_LOWER_F          = 0xCF,
   CTRLM_KEY_CODE_LOWER_G          = 0xD0,
   CTRLM_KEY_CODE_LOWER_H          = 0xD1,
   CTRLM_KEY_CODE_LOWER_I          = 0xD2,
   CTRLM_KEY_CODE_LOWER_J          = 0xD3,
   CTRLM_KEY_CODE_LOWER_K          = 0xD4,
   CTRLM_KEY_CODE_LOWER_L          = 0xD5,
   CTRLM_KEY_CODE_LOWER_M          = 0xD6,
   CTRLM_KEY_CODE_LOWER_N          = 0xD7,
   CTRLM_KEY_CODE_LOWER_O          = 0xD8,
   CTRLM_KEY_CODE_LOWER_P          = 0xD9,
   CTRLM_KEY_CODE_LOWER_Q          = 0xDA,
   CTRLM_KEY_CODE_LOWER_R          = 0xDB,
   CTRLM_KEY_CODE_LOWER_S          = 0xDC,
   CTRLM_KEY_CODE_LOWER_T          = 0xDD,
   CTRLM_KEY_CODE_LOWER_U          = 0xDE,
   CTRLM_KEY_CODE_LOWER_V          = 0xDF,
   CTRLM_KEY_CODE_LOWER_W          = 0xE0,
   CTRLM_KEY_CODE_LOWER_X          = 0xE1,
   CTRLM_KEY_CODE_LOWER_Y          = 0xE2,
   CTRLM_KEY_CODE_LOWER_Z          = 0xE3,
   CTRLM_KEY_CODE_QUESTION         = 0xE4,
   CTRLM_KEY_CODE_EXCLAMATION      = 0xE5,
   CTRLM_KEY_CODE_POUND            = 0xE6,
   CTRLM_KEY_CODE_DOLLAR           = 0xE7,
   CTRLM_KEY_CODE_PERCENT          = 0xE8,
   CTRLM_KEY_CODE_AMPERSAND        = 0xE9,
   CTRLM_KEY_CODE_ASTERISK         = 0xEA,
   CTRLM_KEY_CODE_LEFT_PAREN       = 0xEB,
   CTRLM_KEY_CODE_RIGHT_PAREN      = 0xEC,
   CTRLM_KEY_CODE_PLUS             = 0xED,
   CTRLM_KEY_CODE_MINUS            = 0xEE,
   CTRLM_KEY_CODE_EQUAL            = 0xEF,
   CTRLM_KEY_CODE_FORWARD_SLASH    = 0xF0,
   CTRLM_KEY_CODE_UNDERSCORE       = 0xF1,
   CTRLM_KEY_CODE_DOUBLE_QUOTE     = 0xF2,
   CTRLM_KEY_CODE_COLON            = 0xF3,
   CTRLM_KEY_CODE_SEMICOLON        = 0xF4,
   CTRLM_KEY_CODE_COMMERCIAL_AT    = 0xF5,
   CTRLM_KEY_CODE_APOSTROPHE       = 0xF6,
   CTRLM_KEY_CODE_COMMA            = 0xF7,
   CTRLM_KEY_CODE_INVALID          = 0xFF
} ctrlm_key_code_t;

#endif
